SourceCode <- function(Root = "/Users/fredcommo/Documents/Projet Safir/"){
	#Chargement des packages R
	cat('Loading R packages...\n')
	require(limma)
	require(DNAcopy)
	require(preprocessCore)
	require(AMORE)
	require(affy)
	require(robustbase)
	require(mclust)
	require(tcltk)
	require(annotate)
	require(XML)
	require(R2HTML)

	# Chargement des modules R
	cat('Loading CGH workflow...\n')
	setwd(paste(Root, 'Safir R Sources/', sep =''))
	source("loadAffy.v2.1.R")
	source('loadAgilent.v3.R')
	source("NormCGH.v6.2.R")
	source("MSegments.R")
	source("QCprofile.v2.R")
	source("AddSegments.R")
	source("greq.val.v2.R")
	source("dLRsd.R")
	source("Plot.cgh.v5.1.R")
	source("plotFocus.R")
	source("GeneRequest.v5.R")
	source("SaveSafir.v2.R")
	source("EditTab.v1.2.R")
	source("EditInfos.R")
	source("EditSupTab.v7.6.R")
	source("CAAI.4.R")
	source("WAAI.R")
}

SourceCode()
cat('R functions successfully loaded... Lucky you!\n')
